name: Comment automatically when labeled

on:
  issues:
    types: [labeled]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on issue
      uses: actions/github-script@v7
      with:
        script: |
          const issue = context.issue;
          const label = context.payload.label;
          if (label.name === "审核通过") {
            github.issues.createComment({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "您的申请已通过，欢迎加入开往大家庭～\n约10分钟后您便可以在[开往成员列表](https://list.travellings.cn)搜索到您的网站~\n开往的QQ群：186690715"
            });
          }
